### PR TITLE
Add support for specifying relative images directory

### PR DESCRIPTION
**Pull request by jcowgill**

### CODE REVIEW

**Comment by bharadwaj-raju** [comment]
I suppose the full path substitution is done by the shell, we don't need to do it.

**Comment by jcowgill** [comment]
I'm talking about calls like this: `python3 WeatherDesk.py -d images`
Why would the shell expand it? It doesn't even though "images" being used as a path.

**Comment by bharadwaj-raju** [comment]
So... currently it doesn't work?

**Comment by bharadwaj-raju** [comment]
Well, it can't hurt to get the `abspath()`, so merging.

**Comment by jcowgill** [comment]
It doesn't work at the moment if you use a relative directory. For GNOME it would set the key to 'images/<file>' but GNOME has no idea where the images directory is and I get a black screen.

**Pull request merged**
