### PR TITLE
Time only flag

### PR DESCRIPTION
**Pull request by AKuederle**
Added an option to disable the weather functionality. With the `--no-weather` flag WeatherDesk will need no internet functionality and will only use the time of the day to change the wallpaper.

Would be cool if someone second could verify, that this works correctly.

### CODE REVIEW

**Comment by bharadwaj-raju** [comment]
Another good pull request!

Minor error: in the README, in the naming of files section, there is this:

>```
>If you use --no-weather, the files have to be named simply after the time of day depending of your 
>time schema.
>E.g.: "day.{0}", "night.{0}"
>```

I think you meant to use Python's `str.format()` to do something with those `{0}`s?

Fix that and this is ready to pull!

**Comment by AKuederle** [comment]
Oh you are right. I will check whats going on there.

**Comment by AKuederle** [comment]
Ok it was just copy-and-paste blindness I guess.

**Comment by bharadwaj-raju** [comment]
I also fixed it in the output of `--naming` in WeatherDesk.py just now.

Thanks a lot for taking the time out to help!

**Comment by AKuederle** [comment]
Sure thing!

**Pull request merged**
